swagger: '2.0'
info:
  title: "用户权限管理"
  description: ""
  version: "1.0.0"
host: localhost:3000
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
paths:
  /auth:
    post:
      summary: api访问权限校验
      tags:
        - auth
      parameters:
        - in: header
          name: X-Original-Method
          type: string
          required: true
          description: api请求的httpMethod
        - name: X-Original-URI
          type: string
          in: header
          required: true
          description: api请求的url
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /users/me/pages:
    get:
      summary: 获取当前用户可访问的菜单项
      tags:
        - pages
      responses:
        200:
          description: 成功返回用户可访问的菜单项
          schema:
            type: object
            required:
              - payload
            properties:
              message:
                type: string
              payload:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - title
                  properties:
                    id:
                      type: string
                      description: pageId
                    icon:
                      type: string
                      description: 图标
                    title:
                      type: string
                      description: 标题
                    url:
                      type: string
                    items:
                      type: array
                      items:
                        type: object
                        required:
                          - id
                          - title
                        properties:
                          id:
                            type: string
                          icon:
                            type: string
                          title:
                            type: string
                          url:
                            type: string
  /users/me/pages/{id}:
    get:
      summary: 获取指定页当前用户的权限
      tags:
        - pages
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: 页面id
      responses:
        200:
          description: OK
          schema:
            type: object
            required:
              - payload
            properties:
              message:
                type: string
              payload:
                type: array
                items:
                  type: string
                  description: 业务操作
                example:
                  - editable
  /users:
    get:
      summary: 根据条件查询用户信息
      tags:
        - users
      parameters:
        - name: name
          type: string
          in: query
          description: 用户姓名
        - in: query
          name: roleId
          type: array
          items:
            type: string
          collectionFormat: pipes
          description: 角色Id
        - in: query
          name: status
          type: integer
          description: &user-status-description |
            0 - 冻结
            2 - 有效
          enum: [0, 2]
        - $ref: '#/parameters/PageSize'
        - $ref: '#/parameters/PageIndex'
        - $ref: '#/parameters/SortField'
        - $ref: '#/parameters/IsDesc'
      responses:
        200:
          description: 用户信息列表
          schema:
            type: object
            required:
              - payload
            properties:
              message:
                type: string
              payload:
                type: object
                allOf:
                  - type: object
                    required:
                      - content
                    properties:
                      content:
                        type: array
                        items:
                          type: object
                          required:
                            - id
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            username:
                              type: string
                            status:
                              type: integer
                              description: &user-status-description |
                                0 - 冻结
                                2 - 有效
                              enum: [0, 2]
                            roles:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  name:
                                    type: string
                            options:
                              type: array
                              items:
                                type: string
                                description: &user-options-description |
                                  editable    - 是否可编辑
                                  disableOrEnable - 是否可冻结或解冻
                              enum: ["editable","disableOrEnable"]
                  - $ref: '#/definitions/Paging'
    post:
      summary: 新增用户
      tags:
        - users
      parameters:
        - in: body
          name: user
          description: 用户信息
          schema:
            type: object
            required:
              - name
              - username
              - password
            properties:
              name:
                type: string
              username:
                type: string
              password:
                type: string
              roles:
                type: array
                items:
                  type: string
                  description: 角色Id
      responses:
        201:
          description: Created
  /users/{id}:
    get:
      summary: 用户详细信息
      tags:
        - users
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: 用户Id
      responses:
        200:
          description: OK
          schema:
            type: object
            required:
              - payload
            properties:
              message:
                type: string
              payload:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  username:
                    type: string
                  status:
                    type: integer
                    description: 状态
                  roles:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                  options:
                      type: array
                      items:
                        type: string
                        description: &user-options-description |
                          editable    - 是否可编辑
                          disableOrEnable - 是否可冻结或解冻
                      enum: ["editable","disableOrEnable"]
    put:
      summary: 修改
      tags:
        - users
      parameters:
        - in: path
          name: id
          description: 用户id
          type: string
          required: true
        - in: body
          name: user
          description: 用户信息
          required: true
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              roles:
                type: array
                items:
                  type: string
                  description: 角色id
      responses:
        200:
          description: OK
  /users/{id}/disable:
    put:
      summary: 冻结用户
      tags:
        - users
      parameters:
        - in: path
          name: id
          description: 用户id
          type: string
          required: true
      responses:
        200:
          description: Ok
  /users/{id}/enable:
    put:
      summary: 解冻用户
      tags:
        - users
      parameters:
        - in: path
          name: id
          description: 用户id
          type: string
          required: true
      responses:
        200:
          description: OK
  /roles:
    get:
      summary: 获取角色列表
      tags:
        - roles
      parameters:
        - in: query
          name: status
          type: integer
          required: true
          description: &role-status-description |
            0 - 作废
            2 - 有效
          enum: [0, 2]
      responses:
        200:
          description: 角色列表
          schema:
            type: object
            required:
              - payload
            properties:
              message:
                type: string
              payload:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - name
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    options:
                      type: array
                      items:
                        type: string
                        description: &role-options-description |
                          editable    - 是否可编辑
                          abandonable - 是否可作废
                      enum: ["editable","abandonable"]
    post:
      summary: 新增角色
      tags:
        - roles
      parameters:
        - in: body
          name: role
          description: 角色
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              operations:
                type: array
                items:
                  type: string
                  description: 业务操作Id
              pages:
                type: array
                description: 可访问的页面
                items:
                  type: string
                  description: 页面Id
      responses:
        201:
          description: Created
  /roles/{id}:
    put:
      summary: 修改角色
      tags:
        - roles
      parameters:
        - in: path
          name: id
          description: 角色Id
          required: true
          type: string
        - in: body
          name: role
          description: 角色
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: 角色名称
              status:
                type: integer
                description: 角色状态
              operations:
                type: array
                items:
                  type: string
                  description: 业务操作Id
              pages:
                type: array
                description: 可访问的页面
                items:
                  type: string
                  description: 页面Id
      responses:
        200:
          description: OK
    get:
      summary: 获取角色详情
      tags:
        - roles
      parameters:
        - in: path
          name: id
          type: string
          required: true
          description: 角色Id
      responses:
        200:
          description: 权限列表
          schema:
            type: object
            required:
              - payload
            properties:
              message:
                type: string
              payload:
                type: object
                required:
                  - permissions
                properties:
                  id:
                    type: string
                    description: 角色id
                  name:
                    type: string
                    description: 角色名
                  options:
                    type: array
                    items:
                      type: string
                      description: &role-options-description |
                        editable    - 是否可编辑
                        abandonable - 是否可作废
                    enum: ["editable","abandonable"]
                  permissions:
                    description: 角色对应的权限，为了方便在界面展示，以page层次结构返回
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - name
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        items:
                          type: array
                          items:
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                              operations:
                                type: array
                                items:
                                  $ref: '#/definitions/Permission'
  /roles/{id}/info:
    put:
      summary: 修改角色权限以外的信息
      tags:
        - roles
      parameters:
        - in: path
          name: id
          description: 角色id
          required: true
          type: string
        - in: body
          name: role
          description: 角色
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: 角色名称
      responses:
        200:
          description: OK
  /roles/{id}/abandon:
    put:
      summary: 作废角色
      tags:
        - roles
      parameters:
        - in: path
          name: id
          description: 角色id
          required: true
          type: string
      responses:
        200:
          description: OK
  /pages:
    get:
      summary: 获取page列表
      parameters:
        - in: query
          name: maxLevel
          type: integer
          description: 最大层级
      tags:
        - roles
      responses:
        200:
          description: page列表
          schema:
            type: object
            required:
              - payload
            properties:
              message:
                type: string
              payload:
                type: array
                items:
                  $ref: '#/definitions/PageList'
  /pages/{id}:
    get:
      summary: 获取page详情
      description: 当前页面的子页面和业务操作的信息
      tags:
        - roles
      parameters:
        - in: path
          name: id
          type: integer
          required: true
      responses:
        200:
          description: 业务操作列表
          schema:
            type: object
            required:
              - payload
            properties:
              message:
                type: string
              payload:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  items:
                    type: array
                    items:
                      $ref: '#/definitions/PageListIncludePermission'
                  operations:
                    type: array
                    items:
                      $ref: '#/definitions/Permission'
definitions:
  Paging:
    description: 分页信息
    required:
      - totalElements
    properties:
      pageIndex:
        type: integer
        format: int32
        description: 当前页码
      pageSize:
        type: integer
        format: int32
        description: 每页显示数量
      sort:
        $ref: '#/definitions/Sort'
      totalElements:
        type: integer
        format: int64
        description: 总命中条数
        minimum: 0
      totalPages:
        type: integer
        format: int32
        description: 总命中页数
  Sort:
    type: object
    description: 排序方式 ASC生序 DESC降序
  Permission:
    properties:
      id:
        type: string
      name:
        type: string
  PageList:
    description: page列表
    required:
      - id
      - name
    properties:
      id:
        type: string
        description: pageId
      name:
        type: string
        description: page名字
      items:
        type: array
        items:
          properties:
            id:
              type: string
              description: pageId
            name:
              type: string
              description: page名字
            operationCount:
              type: integer
              description: 包含的业务操作个数，用来控制页面上page树的勾选状态
            itemCount:
              type: integer
              description: 子节点数，用来控制页面上page树的勾选状态
  PageListIncludePermission:
    description: 返回page及其对应的业务操作
    properties:
      id:
        type: string
        description: pageId
      name:
        type: string
        description: page名字
      items:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
      operations:
        type: array
        items:
          properties:
            id:
              type: string
              description: 业务操作Id
            name:
              type: string
              description: 业务操作名称
parameters:
  PageSize:
    name: pageSize
    in: query
    description: 每页数据量
    type: integer
    default: 20
    minimum: 10
  PageIndex:
    name: pageIndex
    in: query
    description: 指定页
    type: integer
    default: 0
    minimum: 0
  SortField:
    name: sortField
    in: query
    description: 排序字段
    type: string
    default: createTime
  IsDesc:
    name: isDesc
    in: query
    description: 倒序排列
    type: boolean
    default: false
    allowEmptyValue: true
